SWUTILS-806: Include PCIe Slot/Gen info to sfreport 'dmidecode -t slot'
Xilinx-CNS/sfreport pull request #26
Opened 2024-09-25 08:58 UTC by amitgu-xilinx

Also fixes [SWUTILS-941](https://jira.xilinx.com/browse/SWUTILS-941)

2024-10-02 11:00 UTC, dchadwic-xilinx requested changes
Test

2024-10-02 11:07 UTC, amitgu-xilinx commented
dmidecode -t slot |grep -b10  'PCI Express' 
might work better.

2024-11-25 14:00 UTC, amitgu-xilinx commented
Have update. Can you please test on your servers.

2025-01-02 15:52 UTC, merged

2025-01-02 15:53 UTC, dchadwic-xilinx commented
Tested on my systems.